server:
  port: 8080

spring:
  application:
    name: reactive-hexagonal
    
  docker:
    compose:
      enabled: false

  # POSTGRESQL (R2DBC)
  r2dbc:
    #url: r2dbc:postgresql://168.119.122.86:5432/yowyob
    url: r2dbc:postgresql://localhost:5432/reactivedb
    #username: master
    username: user
    #password: Azerty1234*
    password: password

  sql:
    init:
      mode: always

  # REDIS CLUSTER 
  data:
    redis:
      host: localhost
      port: 6379
      password: Azerty1234*
      cluster:
        enabled: false 

  # KAFKA 
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# CUSTOM CONFIG 
application:
  external:
    stock-service-url: http://localhost:8081

  kafka:
    topics:
      product-events: product-events-topic

# AUTH SERVICE
auth:
  service:
    url: https://auth-service.pynfi.com

# RESILIENCE4J 
resilience4j:
  circuitbreaker:
    instances:
      stock-service:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        slidingWindowSize: 5
