server:
  port: 8080
  forward-headers-strategy: framework
spring:
  application:
    name: vehicule-service
    
  docker:
    compose:
      enabled: false
  # Configuration Multipart (Uploads)
  webflux:
    multipart:
      max-in-memory-size: 256KB # Taille en RAM avant écriture disque (si besoin)
      max-file-size: 10MB       # Taille max d'un fichier
      max-request-size: 10MB    # Taille max de la requête totale

  # Configuration des Codecs (Pour éviter les erreurs "DataBufferLimitException")
  codec:
    max-in-memory-size: 10MB

  # POSTGRESQL (R2DBC)
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:reactivedb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
    pool:
      enabled: true
      initial-size: 1
      max-size: 5
      max-idle-time: 30m
      max-life-time: 10m
      acquire-retry: 3
      max-acquire-time: 30s
      validation-query: SELECT 1
  sql:
    init:
      mode: always

  # REDIS CLUSTER 
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:7000}
      password: ${REDIS_PASSWORD:password}
      cluster:
        enabled: false

  # KAFKA 
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# CUSTOM CONFIG 
application:
  external:
    stock-service-url: http://${EXTERNAL_HOST:localhost}:8081
    media-service-url: https://media-service.pynfi.com

  kafka:
    topics:
      product-events: product-events-topic

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","prometheus"]
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# AUTH SERVICE
auth:
  service:
    url: https://auth-service.pynfi.com

# RESILIENCE4J 
resilience4j:
  circuitbreaker:
    instances:
      stock-service:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        slidingWindowSize: 5
