name: Spring Boot CI/CD

on:
  push:
    branches:
      - "**"
      #- main

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/vehicule-service
  APP_NAME: vehicule-service
  HEALTH_DELAY: ${{ secrets.DEPLOY_DELAY }}
  CONTAINER_NAME: vehicule-service

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Run Unit Tests + SonarQube Analysis
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=${{ env.APP_NAME }} \
            -Dsonar.projectName=${{ env.APP_NAME }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}

  build:
    needs: tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ secrets.REGISTRY_NAMESPACE }} --password-stdin

      - name: Use prod.application.yml
        run: |
          echo "Using prod.application.yml"
          rm src/main/resources/application.yml
          mv src/main/resources/prod.application.yml src/main/resources/application.yml
          cat src/main/resources/application.yml

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.REGISTRY_IMAGE }}:latest .

      - name: Push Docker image
        run: |
          echo "Pushing Docker image..."
          docker push ${{ env.REGISTRY_IMAGE }}:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'

            echo "Pulling latest image ${{ env.REGISTRY_IMAGE }}"

            docker login ghcr.io -u ${{ secrets.REGISTRY_NAMESPACE }} -p ${{ secrets.PERSONAL_ACCESS_TOKEN }}

            cd /root/projet_synthese/infra

            echo "Stopping container"
            docker compose down ${{ env.CONTAINER_NAME }}

            echo "Removing old image"
            docker rmi -f ${{ env.REGISTRY_IMAGE }}:latest || true

            echo "Pulling new image"
            docker pull ${{ env.REGISTRY_IMAGE }}:latest

            echo " Starting container"
            docker compose up -d ${{ env.CONTAINER_NAME }}

            echo " Waiting ${{ env.HEALTH_DELAY }} seconds for health check"
            sleep ${{ env.HEALTH_DELAY }}

            echo " Checking container health..."
            STATUS=$(docker inspect --format='{{json .State.Health.Status}}' ${{ env.CONTAINER_NAME }})

            echo "Health status: $STATUS"

            if [ "$STATUS" != "\"healthy\"" ]; then
              echo "ERROR: Container is not healthy"
              exit 1
            fi

            echo "Deployment successful & container healthy!"
          EOF


